### PR TITLE
Add aead_encrypt and aead_decrypt convenience functions

### PR DESCRIPTION
**Pull request by thibault-martinez**
## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Wollac — COMMENTED** [review]
Two remarks:
- While I am not aware of any particular specification and there are cases with a different order, I would say the "usual" order is `nonce || ciphertext || tag`. So should we also maybe use that order here?
- I absolutely agree, we should add such a util function. Especially since `associated_data` and `tag` is hardly ever needed explicitly. However, I see this a bit differently for the nonce. There are common scenarios where the nonce is not chosen randomly, e.g. all-zero for ephemeral keys or derived from a hash. Good arguments can be made, why the nonce should still be explicit (like e.g. in crypto_secretbox_easy and libsodium is usually a great example for API design).
However, nonce selection is security critical. So, when this better fits the use-case your are having in mind, let's leave it like this and hide the nonce.

**Comment by thibault-martinez** [comment]
> * While I am not aware of any particular specification and there are cases with a different order, I would say the "usual" order is `nonce || ciphertext || tag`. So should we also maybe use that order here?

I kind of assumed that was the usual order as it has been chosen this way for the stronghold integration in the wallet. We obviously can't change it now. I would understand if choosing an arbitrary order was a no-go for an inclusion in crypto.rs

>   However, nonce selection is security critical. So, when this better fits the use-case your are having in mind, let's leave it like this and hide the nonce.

I am not fully certain what your conclusion is. Do you want me to make the nonce a parameter?

**Comment by Wollac** [comment]
If that order is already in use let's stick with it :+1: 
Maybe you could add a comment describing the order and that the nonce is initialized randomly.

**Review by Wollac — APPROVED** [review]

**Comment by thibault-martinez** [comment]
> Maybe you could add a comment describing the order and that the nonce is initialized randomly.

Done, let me know if this is fine.

**Pull request merged**
