### PR TITLE
Enable segment field access

### PR DESCRIPTION
**Pull request by bingyanglin**
# Description of change

Enable `Segment` field access to enable python binding for iota.rs usage.

## Type of change

- [X] Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Compiled and tested pass.

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Thoralf-M — APPROVED** [review]

**Review by nothingismagick — APPROVED** [review]
Lets let @Wollac approve then merge. OK?

**Comment by bingyanglin** [comment]
> Lets let @Wollac approve then merge. OK?

Sure.

**Review by Wollac — APPROVED** [review]
lgtm

**Comment by bingyanglin** [comment]
Would you please help merge this? I am not authorized to merge. Thanks!

**Pull request merged**
